---
abstract: 'programmatic XML generation, conveniently'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Builder
requires:
  Carp::Clan: 0
  Encode: 0
  Object::Tiny::Lvalue: 0
  Scalar::Util: 0
  overload: 0
  parent: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/XML-Builder/issues
  homepage: http://github.com/ap/XML-Builder
  repository: git://github.com/ap/XML-Builder
version: 0.904
