---
abstract: 'programmatic XML generation, conveniently'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101550, CPAN::Meta::Converter version 2.101461'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Builder
requires:
  Carp::Clan: 0
  Encode: 0
  Object::Tiny::Lvalue: 0
  Scalar::Util: 0
  parent: 0
resources:
  homepage: http://github.com/ap/XML-Builder
  repository: git://github.com/ap/XML-Builder
version: 0.902
